# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 316d73216a69b64586d3b91ddb0d3825f05f5531f04738c0f17b108082512615a32c825e969bfae11eb275ed71d78016ce0ce41ac99d9e1f0a865508c8e230a8

test:
  secret_key_base: 1cd2e8b573ff94be9d90cae75e6ee3617a421ab87b06bd98ccdb28d2aeeaba81813a1d5f5c526e17f427f016296377d1820d0b987543a68f80850ade2f8b6f59

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
